name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3

      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build application
        run: pnpm run build

      - name: Publish releases
        uses: samuelmeuli/action-electron-builder@v1
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          release: true # ${{ startsWith(github.ref, 'refs/tags/v') }}
