name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3

      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build app
        run: pnpm run build

      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm run release

      - name: Copy AppImage and Python script to a new directory
        run: mkdir prepare && cp release/*.AppImage prepare && mkdir prepare/src && mkdir prepare/src/utils cp src/utils/*.py prepare/src/utils && cd prepare && mkdir temp

      - name: Zip the prepare directory
        run: zip -r prepare.zip prepare

      - name: See directory
        run: ls -la && ls -la prepare

      - name: Upload to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: prepare.zip
          asset_name: Release
          overwrite: true
          body: "This is my release text"
